[versions]
application_id = "com.ohyooo.jpsyllabary"
min_sdk = "21"
target_sdk = "35"
compile_sdk = "35"
version_code = "33"
version_name = "3.1"

agp = "8.8.0"
kotlin = "2.1.10"
compose = "1.7.6"

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
alp = { id = "com.android.library", version.ref = "agp" }
kgp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ks = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmm = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jc = { id = "org.jetbrains.compose", version = "1.8.0-dev1905" }
cc = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
# Kotlin
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.8.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1"

# Compose
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }


# AndroidX
androidx-core-ktx = "androidx.core:core-ktx:1.15.0"
activity-compose = "androidx.activity:activity-compose:1.10.0"
startup-runtime = "androidx.startup:startup-runtime:1.2.0"

